# Generated by Django 3.2.6 on 2021-08-16 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Название категории')),
                ('description', models.TextField(verbose_name='Описание категории')),
                ('image', models.ImageField(upload_to='categories_images/', verbose_name='Изображение')),
                ('slug', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='CategoryRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Название комнаты')),
                ('type_of_room', models.BooleanField(default=False, help_text='По дефолту открыта')),
                ('description', models.TextField(verbose_name='Описание комнаты')),
                ('image', models.ImageField(upload_to='category_rooms_images/', verbose_name='Изображение')),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='sh_blog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Комната категории',
                'verbose_name_plural': 'Комнаты категорий',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Название статьи')),
                ('body', models.TextField()),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='sh_blog.categoryrooms', verbose_name='Комната')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Название мира')),
                ('description', models.TextField(verbose_name='Описание мира')),
                ('image', models.ImageField(upload_to='worlds_images/', verbose_name='Изображение')),
                ('slug', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Мир',
                'verbose_name_plural': 'Миры',
            },
        ),
        migrations.CreateModel(
            name='TopicRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Название комнаты')),
                ('type_of_room', models.BooleanField(default=False, help_text='По дефолту открыта')),
                ('description', models.TextField(verbose_name='Описание комнаты')),
                ('image', models.ImageField(upload_to='topic_rooms_images/', verbose_name='Изображение')),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='sh_blog.topic', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Комната статьи',
                'verbose_name_plural': 'Комнаты статей',
            },
        ),
        migrations.CreateModel(
            name='TopicImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название изображения')),
                ('description', models.TextField(max_length=500, verbose_name='Описание изображения')),
                ('image', models.ImageField(upload_to='topics_images/', verbose_name='Изображение')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_images', to='sh_blog.topic', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Изобрежение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='RoomsProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Название проэкта')),
                ('type_of_project', models.BooleanField(default=False, help_text='По дефолту открыт')),
                ('description', models.TextField(verbose_name='Описание проэкта')),
                ('image', models.ImageField(upload_to='rooms_projects_images/', verbose_name='Изображение')),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='sh_blog.topicrooms', verbose_name='Комната')),
            ],
            options={
                'verbose_name': 'Проэкт комнаты',
                'verbose_name_plural': 'Проэкты комнат',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='sh_blog.world', verbose_name='Мир'),
        ),
    ]
