# Generated by Django 3.2.6 on 2021-08-16 15:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sh_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Датта создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoryrooms',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Датта создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomsprojects',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Датта создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Датта создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Датта редактирования'),
        ),
        migrations.AddField(
            model_name='topicrooms',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Датта создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='world',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Датта создания'),
            preserve_default=False,
        ),
    ]
