# Generated by Django 3.2.6 on 2021-08-24 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sh_blog', '0003_auto_20210823_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomsprojects',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='sh_blog.topicrooms', verbose_name='Комната'),
        ),
    ]
