# Generated by Django 3.2.6 on 2021-08-24 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sh_blog', '0004_alter_roomsprojects_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomsprojects',
            name='body',
            field=models.TextField(blank=True, verbose_name='Полное описание проэкта'),
        ),
        migrations.AlterField(
            model_name='roomsprojects',
            name='description',
            field=models.TextField(verbose_name='Краткое описание проэкта'),
        ),
        migrations.CreateModel(
            name='ProjectsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название изображения')),
                ('description', models.TextField(verbose_name='Описание изображения')),
                ('image', models.ImageField(upload_to='projects_images/', verbose_name='Изображение')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_images', to='sh_blog.roomsprojects', verbose_name='Проэкт')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
